# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deber_pantalla_py.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from base_datos import conn

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 356)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.producto = QtWidgets.QLineEdit(self.centralwidget)
        self.producto.setGeometry(QtCore.QRect(140, 80, 113, 23))
        self.producto.setObjectName("producto")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 54, 15))
        self.label.setObjectName("label")
        self.descripcion = QtWidgets.QLineEdit(self.centralwidget)
        self.descripcion.setGeometry(QtCore.QRect(140, 120, 113, 23))
        self.descripcion.setText("")
        self.descripcion.setObjectName("descripcion")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 61, 20))
        self.label_2.setObjectName("label_2")
        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setGeometry(QtCore.QRect(70, 250, 211, 21))
        self.guardar.setObjectName("guardar")
        self.actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.actualizar.setGeometry(QtCore.QRect(70, 280, 211, 21))
        self.actualizar.setObjectName("actualizar")
        self.listaProductos = QtWidgets.QTableWidget(self.centralwidget)
        self.listaProductos.setGeometry(QtCore.QRect(290, 70, 511, 231))
        self.listaProductos.setObjectName("listaProductos")
        self.listaProductos.setColumnCount(0)
        self.listaProductos.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 54, 15))
        self.label_3.setObjectName("label_3")
        self.precio = QtWidgets.QLineEdit(self.centralwidget)
        self.precio.setGeometry(QtCore.QRect(140, 160, 113, 23))
        self.precio.setText("")
        self.precio.setObjectName("precio")
        self.descuento = QtWidgets.QLineEdit(self.centralwidget)
        self.descuento.setGeometry(QtCore.QRect(140, 200, 113, 23))
        self.descuento.setText("")
        self.descuento.setObjectName("descuento")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 200, 54, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 50, 111, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

         # Manejo de base de datos
        self.crear_base()
        self.obtener_informacion()
        self.guardar.clicked.connect(self.guardar_informacion)
        self.actualizar.clicked.connect(self.obtener_informacion)
        #

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def crear_base(self):
            cursor = conn.cursor()
            cadena_sql = 'CREATE TABLE Producto (nombre TEXT,descripcion TEXT,precio FLOAT, descuento FLOAT, precioFinal FLOAT)'
            try:
                cursor.execute(cadena_sql)
            except:
                pass
            cursor.close()
    
    def guardar_informacion(self):
        cursor = conn.cursor()
        producto = str(self.producto.text())
        descripcion = str(self.descripcion.text())
        precio = float(self.precio.text())
        descuento = float(self.descuento.text())
        precioFinal = precio-descuento
        cadena_sql = """INSERT INTO Producto (nombre, descripcion, precio, descuento, precioFinal) VALUES ('%s','%s',%s, %s, %s);""" % \
    (producto, descripcion, precio, descuento, precioFinal)
        # ejecutar el SQL
        cursor.execute(cadena_sql)
        # confirmar los cambios
        conn.commit()
        cursor.close()

    def obtener_informacion(self):
        cursor = conn.cursor()
        cadena_consulta_sql = "SELECT * from Producto"
        cursor.execute(cadena_consulta_sql)
        informacion = cursor.fetchall()
        database_table_column_count = 5
        self.listaProductos.setColumnCount(database_table_column_count)
        numero_filas = len(informacion)
        self.listaProductos.setRowCount(numero_filas)
        for j in range(numero_filas):
            valor = informacion[j]
            for i in range(0, len(valor)):
                elemento = valor[i]
                elemento = str(elemento)
                nuevo_registro = QtWidgets.QTableWidgetItem(elemento)
                self.listaProductos.setItem(j, i, nuevo_registro)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Producto"))
        self.label_2.setText(_translate("MainWindow", "Descripcion"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.actualizar.setText(_translate("MainWindow", "Actualizar"))
        self.label_3.setText(_translate("MainWindow", "Precio"))
        self.label_4.setText(_translate("MainWindow", "Descuento"))
        self.label_5.setText(_translate("MainWindow", "Listado de productos"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
